### ISSUE TITLE
ASN1_STRING string length != 13 in brsa_publickey_export_spki()

### ISSUE THREAD

**Issue by callumdmay** [jedisct1/blind-rsa-signatures#2]
Running into an issue where the string length check at blind_rsa.c:810 fails.

The string length check fails because algor_mgf1_s is length 15, not 13. I'm not familiar with this crypto, but here are the 15 bytes:

30 5c 72 5c 78 36 5c 74 60 e2 80 a0 48 5c 78

If its helpful I'm using boringSSL for the crypto operations, and my context was init'd in the default way:
brsa_context_init_default

**Comment by jedisct1** [comment]
For some reason, BoringSSL seems to add an empty record after the ID of the MGF.

This has been fixed in the Zig version. I don't have enough battery left to back port the change to the C version, but the changes would be similar.

Thanks for reporting this!

**Comment by callumdmay** [comment]
Can we leave this open until it's fixed? Someone may want to take this up and it is more visible if it's open
